"""Init

Revision ID: 38334c70a979
Revises: eb9a1291255e
Create Date: 2023-07-28 16:48:34.078376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38334c70a979'
down_revision = 'eb9a1291255e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
