"""Init

Revision ID: 38578059a29c
Revises: d363d7d98bdf
Create Date: 2023-08-02 11:07:15.494892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38578059a29c'
down_revision = 'd363d7d98bdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('qr_code', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('transformed_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'transformed_image_url')
    op.drop_column('photos', 'qr_code')
    # ### end Alembic commands ###
