"""Init

Revision ID: 930f69da9bfa
Revises: 38578059a29c
Create Date: 2023-08-02 13:28:12.880356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930f69da9bfa'
down_revision = '38578059a29c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
